with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/Alienbushman/go-grpc-playground/internal/repository:
    config:
      dir: mocks/repository
      outpkg: mockrepository
    interfaces:
      ItemRepository:
